resources:
  repositories:
  - repository: Angular_DotNET_Projects # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com_purushothamreddyaccionlabs
    name: purushothamreddyaccionlabs/Angular_DotNET_Projects
    ref: refs/heads/master
    trigger:
     branches:
         include:
             - master


pool:
  vmImage: 'windows-latest'

stages:
- stage: build
  displayName: build application
  jobs:
   - job:
     steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: Write-Host "Hello World"
               
