name: Push directory to another repository
on: push
jobs:
  check-bats-version:
    runs-on: windows-latest
    environment: AZUREPAT
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        AZUREPAT: ${{secrets.AZUREPAT}}
      run: |
         powershell.exe ./SyncGitHubToAzureRepo.ps1 $AZUREPAT
      shell: pwsh
